### ISSUE TITLE
Doesn't list config in app/config

### ISSUE THREAD

**Issue by codeinabox** [voronkovich/ctrlp-symfony2.vim#3]
I noticed that the command `:CtrlPSymfony2Configs` does list any of the config files located in app/config. Happy to submit a PR to fix this.

**Comment by voronkovich** [comment]
Thanks @codeinabox, it would be great if you submit the PR. I use this plugin on Ubuntu Linux and it works fine. I've not tested it on another platforms. Maybe the `find` command works not correctly.

**Comment by voronkovich** [comment]
Sorry, @codeinabox  I've read your issue again and it doesn't make sense why you want this plugin to doesn't list configuration files in the `app/config` directory. Holding configuration files in that folder considered as a best practice,  see http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration

**Comment by codeinabox** [comment]
What I meant is it should be listing the files in `app/config`. I've tried it out on two different Symfony projects and none of the app/configs files are listed.

**Comment by voronkovich** [comment]
Ok, now I got it, but I still don't know how to reproduce and fix this issue. If you know - please, create a PR.
I've tested it on https://github.com/symfony/symfony-demo and it works fine.

**Comment by codeinabox** [comment]
Will do. Have you tried using glob or globpath instead of find?

—

**Comment by voronkovich** [comment]
No, I haven't. Do you think that using `globpath` is better than using `find`?

**Comment by codeinabox** [comment]
Not sure, was thinking it might be better to rely on `globpath` which is built-in to Vim. I'll try to create a PR that indicates how I want it to behave.

**Comment by voronkovich** [comment]
@codeinabox, I'm going to add support of `globpath` (for Windows users), `find` and `ag` (the fastest).
It would be great if you create a PR with your example.

**Comment by codeinabox** [comment]
I am not sure what the issue is, the below test passes yet when I use the plug-in on a real project I never see anything under "app". Could it be something that `ctrlp#symfony2#configs#accept` does to change the path?

``` vim
  it "finds the Symfony config files"
    Expect ctrlp#symfony2#configs#init() == [
      \"/MyBundle/Resources/config/routing.yml",
      \"/MyBundle/Resources/config/services/service.yml",
      \"app/config/config.yml"
      \]
  end

```

**Comment by voronkovich** [comment]
@codeinabox, do you change vim's working directory using `:cd` or `:lcd` commands while you're working on your project?

**Comment by codeinabox** [comment]
Never use that command. I just use CtrlP and Ack to navigate the project

**Comment by voronkovich** [comment]
@codeinabox I think I've fixed this error. Try to use this command again.

**Comment by codeinabox** [comment]
I've tried this in two different projects and in both it only returns the config files under "src"

**Comment by voronkovich** [comment]
@codeinabox, I think this error occurs because the BSD `find` (OS X uses it) command canonicalizes the found results by adding leading slashes for them. I've fixed this. Now it should work fine for you, but you won't launch the tests. I try to fix it later.

**Comment by codeinabox** [comment]
I've updated but the problem still continues

**Comment by voronkovich** [comment]
@codeinabox, try to call `ctrlp#symfony2#configs#init()` in your project and see what it will output:
```viml
:echo ctrlp#symfony2#configs#init()
```

**Comment by voronkovich** [comment]
@codeinabox I've totally rewritten this plugin with using the `globpath` instead of the `find`. Please, update your bundles.

**Comment by codeinabox** [comment]
This is still not working. If I run `echo ctrlp#symfony#configs#init()` I get the following

> ['config/config.yml', 'config/config_dev.yml', 'config/config_prod.yml', 'config/config_test.yml', 'config/constants.yml', 'config/constants_test.yml', 'config/parameters.yml', 'config/parameters.yml.dist', 'config/routing.yml', 'config/routing_dev.yml', 'config/security.yml', 'JS/MyBundleApiBundle/Resources/config/handler/handlers.yml', 'JS/MyBundleApiBundle/Resources/config/helper/helper.yml', 'JS/MyBundleApiBundle/Resources/config/listener/listeners.yml', 'JS/MyBundleApiBundle/Resources/config/manager/factories.yml', 'JS/MyBundleApiBundle/Resources/config/manager/managers.yml', 'JS/MyBundleApiBundle/Resources/config/manager/output.yml','JS/MyBundleApiBundle/Resources/config/repository/repositories.yml', 'JS/MyBundleApiBundle/Resources/config/routing.yml', 'JS/MyBundleApiBundle/Resources/config/security/security.yml', 'JS/MyBundleApiBundle/Resources/config/service/services.yml']

But when I run `CtrlPSymfony2Configs` I just get the following

> config/constants_test.yml
> config/routing_dev.yml
> config/config_test.yml
> config/config_prod.yml
> config/parameters.yml
> config/config_dev.yml
> config/constants.yml
> config/routing.yml
> config/config.yml

**Comment by voronkovich** [comment]
Sorry,  @codeinabox, I haven't any idea about how to fix this issue.

**Comment by codeinabox** [comment]
I wonder if it's possible to properly invoke the plugin in the tests and capture the output returned

**Comment by voronkovich** [comment]
@codeinabox, now this plugin uses `globpath` for searching files, so you can run the tests in your machine.
BTW I think you should check your ctrlp settings. You can see mine here https://github.com/voronkovich/vimrc/blob/master/vimrc#L232

**Comment by codeinabox** [comment]
Problem was at my end, had set max height for results to 10 but didn't realise that also capped the number of results.

**Comment by voronkovich** [comment]
Ok. Anyway, thanks for helping me with this plugin.
